### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by samuelick8** [mosinowo1/WebTech-Project#5]
Technical Suggestions
1. I am not sure why but the instagram and pinterest <a> links do not work, maybe typo because I don't see any error in the code.
2. I would change the table format for your socials on your homepage. The spacing with the table is a little weird, so either adjust the table or switch format.
3. Sitemap at bottom of homepage, Change padding on this so it doesn't expand a ton of space.

Content Suggestions
1. Add brand recommendations
2.  Have various price level options when users are looking for products

**Comment by mosinowo1** [comment]
noted, thank you!
