### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by StarryHe214** [mosinowo1/WebTech-Project#6]
Technical Suggestions

instagram and pinterest links are not working
2.change the padding of the bottom sitemap
Content Suggestions
add more pictures of yourself
provide some recommendations of the clothing/brand/fashion you love.

**Comment by StarryHe214** [comment]
Sorry, please ignore the previous comment.

Technical Suggestions

1. instagram and pinterest links are not working 
2.change the padding of the bottom sitemap
Content Suggestions
1. add more pictures of yourself
2. provide some recommendations of the clothing/brand/fashion you love.

**Comment by mosinowo1** [comment]
noted, thank you!
